var MenuDB = [
  {
    id: "1",
    Name: "Rujak",
    Price: "8000",
    Desc: "Rujak adalah hidangan salad buah dan sayuran tradisional Indonesia, umumnya ditemukan di Indonesia, Malaysia, dan Singapura.",
    Restaurant: "1",
    img: "https://cdn.tasteatlas.com/images/dishrestaurants/0b5a4f49383547a884bae583a5f5e4c2.jpg",
  },
  {
    id: "2",
    Name: "Pecel",
    Price: "10000",
    Desc: "Pecel atau pecal merupakan makanan berasal dari pulau Jawa, makanan ini biasanya dihidangkan dengan bumbu sambal kacang sebagai bahan utamanya dan dicampur dengan aneka jenis sayuran.",
    Restaurant: "1",
    img: "https://3.bp.blogspot.com/-l9XIcybK9Rc/WKphvod0WRI/AAAAAAAAEDo/HhVl_WmaSQQIAxnsvv3LOzPG-5jEgw1mQCLcB/s1600/pecel.jpg",
  },
  {
    id: "3",
    Name: "Pecel Lele",
    Price: "10000",
    Desc: "Pecel lele atau pecek lele di Indonesia adalah nama sebuah makanan khas Jawa yang terdiri dari ikan lele dan sambal tomat.",
    Restaurant: "1",
    img: "https://th.bing.com/th/id/OIP.LlMdyNgBDMnr_DWMtuv50QHaE8?w=261&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "4",
    Name: "Mie Goreng",
    Price: "5000",
    Desc: "Mi goreng berarti mi yang digoreng adalah hidangan mie yang dimasak dengan digoreng tumis khas Indonesia. Mi goreng juga populer dan juga digemari di Malaysia, dan Singapura",
    Restaurant: "2",
    img: "https://th.bing.com/th/id/OIP.zXLgKU_sS_RKNUJGTZ_TaAHaGf?pid=ImgDet&rs=1",
  },
  {
    id: "5",
    Name: "Mie Rebus",
    Price: "5000",
    Desc: "Mie rebus/Mi rebus atau mee rebus adalah sebuah hidangan mi kuah dari Asia Tenggara, yang dikenal di Indonesia, Malaysia, dan Singapura. Hidangan tersebut juga biasa disebut mie kuah.",
    Restaurant: "2",
    img: "https://th.bing.com/th/id/OIP._XNLsDkuO7vsUhvWuKya_QHaEp?pid=ImgDet&rs=1",
  },
  {
    id: "6",
    Name: "Bebek Goreng",
    Price: "12500",
    Desc: "Bebek goreng adalah daging bebek yang digoreng dan dihidangkan dengan lalapan. Bebek goreng dapat ditemui di warung-warung kaki lima sampai di restoran dan hotel mewah.",
    Restaurant: "3",
    img: "https://th.bing.com/th/id/OIP.1fYIChn1AReiAcq2AHrQUwHaE8?w=291&h=194&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "7",
    Name: "Sayur Asem",
    Price: "6000",
    Desc: "Sayur asam atau sayur asem adalah masakan sejenis sayur yang khas Indonesia. Ada banyak variasi lokal sayur asam seperti sayur asam Jakarta, sayur asam kangkung, dan sayur asam ikan asin.",
    Restaurant: "2",
    img: "https://th.bing.com/th/id/OIP.WuV1UwwVzq-bdIDAbQVuFwHaFj?w=219&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "8",
    Name: "Sayur Sop",
    Price: "6500",
    Desc: "Sayur sop adalah sup sayuran Indonesia yang dibuat dari sayuran dalam kaldu ayam atau sapi. Ini populer di Indonesia, disajikan sebagai sarapan atau makan siang.",
    Restaurant: "2",
    img: "https://th.bing.com/th/id/OIP.8mJaLevlv9j5BYDiOXRIIgHaD9?w=315&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "9",
    Name: "Sayur Lodeh",
    Price: "5000",
    Desc: "Sayur lodeh adalah masakan sayur yang berkuah santan khas Indonesia, terutama di daerah Jawa Tengah dan DI Yogyakarta.",
    Restaurant: "2",
    img: "https://th.bing.com/th/id/OIP.LJlbeKniX93_h6KoKsBD5gHaEK?w=313&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "10",
    Name: "Sosis",
    Price: "2000",
    Desc: "Sosis adalah suatu makanan yang terbuat dari daging cincang, lemak hewan, ternak dan rempah, serta bahan-bahan lain, disini kalian bisa menikmatinya dengan cara dibakar",
    Restaurant: "1",
    img: "https://th.bing.com/th/id/OIP.MM3KlwQWneAT7Ujb6N9d7QHaEK?w=297&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "11",
    Name: "Ayam Goreng",
    Price: "6000",
    Desc: "Ayam goreng Nusantara adalah hidangan Asia Tenggara yang merupakan ayam yang digoreng dalam minyak goreng.",
    Restaurant: "3",
    img: "https://media-cdn.tripadvisor.com/media/photo-s/03/24/29/76/talde.jpg",
  },
  {
    id: "12",
    Name: "Usus ayam goreng",
    Price: "5000",
    Desc: "Ayam goreng Nusantara adalah hidangan Asia Tenggara yang merupakan ayam yang digoreng dalam minyak goreng.",
    Restaurant: "3",
    img: "https://cdn1-production-images-kly.akamaized.net/nkCoqFovPFWgftBHfv9hU9Rvz10=/680x383/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2581404/original/094385800_1546593377-menu-buka-sederhana-enaknya-juara-usus-goreng-bumbu-ketumbar.jpg",
  },
  {
    id: "13",
    Name: "Sayur Asem",
    Price: "6000",
    Desc: "Sayur asam atau sayur asem adalah masakan sejenis sayur yang khas Indonesia. Ada banyak variasi lokal sayur asam seperti sayur asam Jakarta, sayur asam kangkung, dan sayur asam ikan asin.",
    Restaurant: "3",
    img: "https://th.bing.com/th/id/OIP.WuV1UwwVzq-bdIDAbQVuFwHaFj?w=219&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "14",
    Name: "Ayam Goreng",
    Price: "6000",
    Desc: "Ayam goreng Nusantara adalah hidangan Asia Tenggara yang merupakan ayam yang digoreng dalam minyak goreng.",
    Restaurant: "4",
    img: "https://media-cdn.tripadvisor.com/media/photo-s/03/24/29/76/talde.jpg",
  },
  {
    id: "15",
    Name: "Usus ayam goreng",
    Price: "5000",
    Desc: "Ayam goreng Nusantara adalah hidangan Asia Tenggara yang merupakan ayam yang digoreng dalam minyak goreng.",
    Restaurant: "4",
    img: "https://cdn1-production-images-kly.akamaized.net/nkCoqFovPFWgftBHfv9hU9Rvz10=/680x383/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/2581404/original/094385800_1546593377-menu-buka-sederhana-enaknya-juara-usus-goreng-bumbu-ketumbar.jpg",
  },
  {
    id: "16",
    Name: "Sayur Asem",
    Price: "6000",
    Desc: "Sayur asam atau sayur asem adalah masakan sejenis sayur yang khas Indonesia. Ada banyak variasi lokal sayur asam seperti sayur asam Jakarta, sayur asam kangkung, dan sayur asam ikan asin.",
    Restaurant: "4",
    img: "https://th.bing.com/th/id/OIP.WuV1UwwVzq-bdIDAbQVuFwHaFj?w=219&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "17",
    Name: "Boba Bubble Tea",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "5",
    img: "https://portalmadura.com/wp-content/uploads/2020/04/boba.jpg",
  },
  {
    id: "18",
    Name: "French Fries Deep Fryer",
    Price: "5500",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "5",
    img: "https://cdn.i-scmp.com/sites/default/files/styles/1200x800/public/d8/images/methode/2019/03/15/55c0d692-4497-11e9-b5dc-9921d5eb8a6d_image_hires_140501.jpg?itok=zzNo_IsD",
  },
  {
    id: "19",
    Name: "Taro ice wafer",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "5",
    img: "https://s-media-cache-ak0.pinimg.com/736x/58/f5/89/58f589204e72dd35f3d2a81d0a178f58.jpg",
  },
  {
    id: "20",
    Name: "Rolling Cheese Beef Ribs",
    Price: "15000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "5",
    img: "https://th.bing.com/th/id/OIP.sJTW8WUNPpcdAVGsPGH_2AHaE8?pid=ImgDet&rs=1",
  },
  {
    id: "21",
    Name: "Easy Pasta Salad",
    Price: "10000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "6",
    img: "https://th.bing.com/th/id/R.09b1d9dd06ef26d2f27ff9c6f9b472a2?rik=5Icz6oZZO4Sn%2bg&riu=http%3a%2f%2fbakerbynature.com%2fwp-content%2fuploads%2f2014%2f08%2fIMG_0588-682x1024-2-682x1024.jpg&ehk=Lk9dbQvk6c3ajFB8AXUK7Rn11nyU4p1AzqYw2bHtS34%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: "22",
    Name: "Special Gado-gado",
    Price: "12000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "6",
    img: "https://144f2a3a2f948f23fc61-ca525f0a2beaec3e91ca498facd51f15.ssl.cf3.rackcdn.com/uploads/food_portal_data/recipes/recipe/hero_article_image/2593/letterbox_GadoGado-593.jpg",
  },
  {
    id: "23",
    Name: "Herbal Tea",
    Price: "8000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "6",
    img: "https://th.bing.com/th/id/OIP.Lh5t3-I5pI2hzP1zjZItdAHaE8?pid=ImgDet&rs=1",
  },
  {
    id: "24",
    Name: "Berbagai Macam jamu",
    Price: "3000 - 10000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "6",
    img: "https://th.bing.com/th/id/OIP.x_pEK3XOa2XxPodie6djiAHaEC?pid=ImgDet&rs=1",
  },
  {
    id: "25",
    Name: "Nasi Kucing",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "7",
    img: "https://th.bing.com/th/id/OIP.euzwDyoQmLk9LvWrVUhTcgHaEj?pid=ImgDet&rs=1",
  },
  {
    id: "26",
    Name: "Sambel Terong",
    Price: "9000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "7",
    img: "https://img-global.cpcdn.com/003_recipes/0e03a7339e2e2a48/751x532cq70/terong-goreng-sambal-lalapan-foto-resep-utama.jpg",
  },
  {
    id: "27",
    Name: "Es ketan hitam",
    Price: "6000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "7",
    img: "https://th.bing.com/th/id/OIP._mGPsSvfvGbyk-vk7DZwdgHaEK?w=285&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "28",
    Name: "Es buah",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "7",
    img: "https://th.bing.com/th/id/OIP.NaY63w3NCI6QTOwXJog_CAHaE9?pid=ImgDet&rs=1",
  },
  {
    id: "29",
    Name: "Nasi Kucing",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "8",
    img: "https://th.bing.com/th/id/OIP.euzwDyoQmLk9LvWrVUhTcgHaEj?pid=ImgDet&rs=1",
  },
  {
    id: "30",
    Name: "Sambel Terong",
    Price: "9000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "8",
    img: "https://img-global.cpcdn.com/003_recipes/0e03a7339e2e2a48/751x532cq70/terong-goreng-sambal-lalapan-foto-resep-utama.jpg",
  },
  {
    id: "31",
    Name: "Es ketan hitam",
    Price: "6000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "8",
    img: "https://th.bing.com/th/id/OIP._mGPsSvfvGbyk-vk7DZwdgHaEK?w=285&h=180&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "32",
    Name: "Es oyen",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "8",
    img: "https://th.bing.com/th/id/OIP.FXtkl8r32Raros2bA6gH8wHaGq?pid=ImgDet&rs=1",
  },
  {
    id: "33",
    Name: "Ayam Bakar Mbul-Mbul",
    Price: "12000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "9",
    img: "https://4.bp.blogspot.com/-ICsTm2-QHzo/V2qqP4237kI/AAAAAAAAJmA/bJFje_yxKDIv9eO3kk2kayMYYcDvQthWwCLcB/s1600/Cara%2BMembuat%2BAyam%2BBakar%2BBetutu%2BBali%2Bdan%2BResep.jpg",
  },
  {
    id: "34",
    Name: "Kari Ayam Spesial",
    Price: "8000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "9",
    img: "https://th.bing.com/th/id/OIP.QSAaKDRNkf_ASdrPUV58sAHaFj?pid=ImgDet&rs=1",
  },
  {
    id: "35",
    Name: "Berbagai Macam Es teh",
    Price: "3000 - 6000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "9",
    img: "https://th.bing.com/th/id/OIP.dx-JeGW_KFehxx9TAurpqwEsDI?pid=ImgDet&rs=1",
  },
  {
    id: "36",
    Name: "Es Jeruk",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "9",
    img: "https://th.bing.com/th/id/OIP.Lg-aNV4EMj4WVCMXcJmkqQHaHa?pid=ImgDet&rs=1",
  },
  {
    id: "37",
    Name: "Nasi Kuning",
    Price: "7000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "10",
    img: "https://th.bing.com/th/id/OIP.USou0XRQBj2cIo_w9m7WHwHaFj?w=267&h=200&c=7&r=0&o=5&pid=1.7",
  },
  {
    id: "38",
    Name: "Nasi Rames",
    Price: "4500",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "10",
    img: "https://img-global.cpcdn.com/recipes/9734c3726f0fcb46/751x532cq70/nasi-rames-foto-resep-utama.jpg",
  },
  {
    id: "39",
    Name: "Es teh",
    Price: "2000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "10",
    img: "https://th.bing.com/th/id/OIP.IakClRuMBuQOHKof4GlWNwHaFY?pid=ImgDet&rs=1",
  },
  {
    id: "40",
    Name: "Nasi Campur",
    Price: "5000",
    Desc: "Boba adalah mutiara atau bola-bola tapioka besar dan kenyal yang terbuat dari tepung tapioka (pati bebas gluten yang diekstrak dari akar tanaman singkong). Mereka mengapung di dalam minuman yang dikenal sebagai bubble tea.",
    Restaurant: "10",
    img: "https://3.bp.blogspot.com/-6lfAWr3C3Ew/WfSRKTXGqvI/AAAAAAABWDM/Wd5Fj758IQ82_IZZfMVbVXVepGpgfdH5wCEwYBhgL/s1600/09%2BBLI_4850%2BMade%2527s%2BWarung%2B-%2BBalinese%2BNasi%2BCampur%2BSpecial%2B%2540%2BKuta%2B%255BBali%2BIsland%252C%2BIndonesia%255D.JPG",
  }
]

var vue = new Vue({
  el: "#app",
  data: {
    Restaurant: {
      id: localStorage.id,
    },
    Menus: MenuDB
  },
  methods: {
    persist(index) {
      localStorage.Menu_id = index.id;
      localStorage.Menu_Name = index.Name;
      localStorage.Menu_Price = index.Price;
      localStorage.Menu_Desc = index.Desc;
      localStorage.Menu_Img = index.img;
    },
  },
});